#ifndef CONFIG_H__
#define CONFIG_H__
#cmakedefine VERSION ${VERSION}
#cmakedefine DATA_DIR ${DATA_DIR}

#cmakedefine DEBUG_ENTRIES_CACHE ${DEBUG_ENTRIES_CACHE}
#cmakedefine DEBUG_PATHS ${DEBUG_PATHS}
#cmakedefine DEBUG_DETAILED_VIEW ${DEBUG_DETAILED_VIEW}
#cmakedefine DEBUG_QUERIES ${DEBUG_QUERIES}
#cmakedefine DEBUG_TRANSACTIONS ${DEBUG_TRANSACTIONS}
#cmakedefine DEBUG_LISTS ${DEBUG_LISTS}

#endif
